# Generated by Django 4.0.1 on 2022-01-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('Updated', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now=True)),
            ],
        ),
    ]
